// services/pdfReportGenerator.ts — Professional Multi-page PDF Report Builder using jsPDF
import { jsPDF } from 'jspdf';
import { PdfInsightReport, SalesRecord, DatasetInfo } from '../types';

/**
 * Generates and downloads a clean, beautifully formatted multi-page PDF executive briefing
 * for Document Intelligence analysis.
 */
export function exportDocumentInsightsToPdf(report: PdfInsightReport): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 40;
  const contentWidth = pageWidth - margin * 2;
  let cursorY = margin;

  const checkPageBreak = (neededHeight: number) => {
    if (cursorY + neededHeight > pageHeight - margin - 20) {
      doc.addPage();
      cursorY = margin + 15;
      renderHeaderFooter();
    }
  };

  const renderHeaderFooter = () => {
    // Top subtle brand line
    doc.setDrawColor(99, 102, 241);
    doc.setLineWidth(1.5);
    doc.line(margin, 25, pageWidth - margin, 25);

    // Running header text
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text('AI BUSINESS STRATEGY ADVISOR • EXECUTIVE INTELLIGENCE BRIEFING', margin, 20);

    // Footer page number
    const pageNum = (doc as any).internal?.pages?.length ? ((doc as any).internal.pages.length - 1) : 1;
    doc.text(`Page ${pageNum}`, pageWidth - margin, pageHeight - 20, { align: 'right' });
    doc.text('Confidential • Generated by Gemini Intelligence Engine', margin, pageHeight - 20);
  };

  renderHeaderFooter();
  cursorY = 50;

  // Header Title Box
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(margin, cursorY, contentWidth, 68, 6, 6, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42);
  const title = report.fileName || 'Executive Document Briefing';
  doc.text(title.length > 50 ? title.substring(0, 48) + '...' : title, margin + 14, cursorY + 24);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(`Classification: ${report.documentType || 'Enterprise Document'}  |  Risk Level: ${report.overallRiskLevel || 'Standard'}`, margin + 14, cursorY + 40);
  doc.text(`Generated: ${report.analyzedAt || new Date().toLocaleString()}  |  Document Pages: ${report.pages?.length || 1}`, margin + 14, cursorY + 54);

  cursorY += 85;

  // Section 1: Executive Summary
  checkPageBreak(80);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(79, 70, 229);
  doc.text('1. EXECUTIVE SUMMARY & NARRATIVE', margin, cursorY);
  cursorY += 14;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(51, 65, 85);
  const summaryLines = doc.splitTextToSize(report.executiveSummary || 'No summary available.', contentWidth);
  doc.text(summaryLines, margin, cursorY);
  cursorY += summaryLines.length * 13 + 16;

  // Section 2: Key Metrics
  if (report.keyMetrics && report.keyMetrics.length > 0) {
    checkPageBreak(100);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(79, 70, 229);
    doc.text('2. KEY EXTRACTED METRICS & KPI BASELINE', margin, cursorY);
    cursorY += 14;

    const colW = contentWidth / Math.min(report.keyMetrics.length, 3);
    report.keyMetrics.slice(0, 6).forEach((m, idx) => {
      checkPageBreak(45);
      const colX = margin + (idx % 3) * colW;
      if (idx > 0 && idx % 3 === 0) {
        cursorY += 45;
      }
      doc.setFillColor(241, 245, 249);
      doc.roundedRect(colX, cursorY, colW - 8, 38, 4, 4, 'F');
      
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(100, 116, 139);
      doc.text(m.label.toUpperCase().substring(0, 22), colX + 8, cursorY + 14);

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.setTextColor(15, 23, 42);
      doc.text(String(m.value), colX + 8, cursorY + 28);
    });
    cursorY += 50;
  }

  // Section 3: Strategic Directives
  if (report.strategies && report.strategies.length > 0) {
    checkPageBreak(80);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(79, 70, 229);
    doc.text('3. STRATEGIC DIRECTIVES & PILLARS', margin, cursorY);
    cursorY += 14;

    report.strategies.forEach((s, idx) => {
      checkPageBreak(50);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(15, 23, 42);
      doc.text(`${idx + 1}. ${s.title}`, margin, cursorY);
      cursorY += 13;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(71, 85, 105);
      const descLines = doc.splitTextToSize(`Directive: ${s.description}`, contentWidth);
      doc.text(descLines, margin + 12, cursorY);
      cursorY += descLines.length * 12;

      if (s.impact) {
        doc.setFont('helvetica', 'italic');
        doc.setTextColor(99, 102, 241);
        doc.text(`Expected Impact: ${s.impact}`, margin + 12, cursorY);
        cursorY += 14;
      }
      cursorY += 4;
    });
    cursorY += 10;
  }

  // Section 4: Action Items
  if (report.recommendedActions && report.recommendedActions.length > 0) {
    checkPageBreak(90);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(79, 70, 229);
    doc.text('4. RECOMMENDED ACTION ROADMAP', margin, cursorY);
    cursorY += 14;

    report.recommendedActions.forEach((a) => {
      checkPageBreak(40);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9.5);
      doc.setTextColor(15, 23, 42);
      doc.text(`[${a.priority.toUpperCase()}] ${a.task}`, margin, cursorY);
      cursorY += 12;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(100, 116, 139);
      doc.text(`Owner: ${a.owner || 'Executive Team'}  |  Target ROI: ${a.expectedRoi || 'Operational Gain'}  |  Page Ref: ${a.pageNumber || 1}`, margin + 12, cursorY);
      cursorY += 16;
    });
    cursorY += 10;
  }

  // Section 5: Risk & Governance
  if (report.risksAndGovernance && report.risksAndGovernance.length > 0) {
    checkPageBreak(80);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(225, 29, 72);
    doc.text('5. RISKS & GOVERNANCE SAFEGUARDS', margin, cursorY);
    cursorY += 14;

    report.risksAndGovernance.forEach((r) => {
      checkPageBreak(38);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(15, 23, 42);
      doc.text(`• [${r.severity.toUpperCase()} RISK] ${r.risk} (Page ${r.pageNumber || 1})`, margin, cursorY);
      cursorY += 12;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(71, 85, 105);
      if (r.mitigation) {
        const mitLines = doc.splitTextToSize(`Safeguard: ${r.mitigation}`, contentWidth - 16);
        doc.text(mitLines, margin + 14, cursorY);
        cursorY += mitLines.length * 11 + 4;
      }
    });
  }

  // Save PDF file
  const cleanName = (report.fileName || 'Executive_Document').replace(/\.[^/.]+$/, '').replace(/[^a-zA-Z0-9_-]/g, '_');
  doc.save(`${cleanName}_Executive_Intelligence.pdf`);
}

/**
 * Exports current dataset and filtered table records to a formatted PDF document.
 */
export function exportDatasetToPdf(
  data: SalesRecord[],
  datasetInfo: DatasetInfo,
  columns: string[]
): void {
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'pt',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 30;
  let cursorY = margin + 15;

  // Header
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text(datasetInfo.name || 'Enterprise Sales Dataset Report', margin, cursorY);
  cursorY += 16;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(100, 116, 139);
  doc.text(`Total Records: ${data.length.toLocaleString()} | Exported: ${new Date().toLocaleString()} | Source: ${datasetInfo.sourceType}`, margin, cursorY);
  cursorY += 20;

  // Render top rows in a clean grid
  const colsToRender = columns.slice(0, 8);
  const colWidth = (pageWidth - margin * 2) / colsToRender.length;

  // Header row
  doc.setFillColor(241, 245, 249);
  doc.rect(margin, cursorY, pageWidth - margin * 2, 18, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(51, 65, 85);
  colsToRender.forEach((col, idx) => {
    doc.text(col.toUpperCase().substring(0, 14), margin + idx * colWidth + 4, cursorY + 12);
  });
  cursorY += 20;

  // Data rows
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(15, 23, 42);

  const sampleRows = data.slice(0, 70);
  sampleRows.forEach((row, rowIdx) => {
    if (cursorY > pageHeight - margin - 20) {
      doc.addPage();
      cursorY = margin + 20;
    }

    if (rowIdx % 2 === 0) {
      doc.setFillColor(248, 250, 252);
      doc.rect(margin, cursorY - 2, pageWidth - margin * 2, 14, 'F');
    }

    colsToRender.forEach((col, cIdx) => {
      const val = String(row[col] ?? '');
      doc.text(val.substring(0, 18), margin + cIdx * colWidth + 4, cursorY + 8);
    });
    cursorY += 14;
  });

  const cleanName = (datasetInfo.name || 'Dataset_Records').replace(/[^a-zA-Z0-9_-]/g, '_');
  doc.save(`${cleanName}_Records_Export.pdf`);
}

/**
 * Downloads a structured template in PDF format with guidance instructions.
 */
export function exportTemplateToPdf(): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 40;
  let cursorY = margin + 20;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(79, 70, 229);
  doc.text('ERP Sales Transaction Dataset Template Specification', margin, cursorY);
  cursorY += 20;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text('Use this schema specification to format your CSV, Excel, or JSON uploads.', margin, cursorY);
  cursorY += 25;

  const schemaItems = [
    { col: 'date', type: 'YYYY-MM-DD', ex: '2024-03-15', desc: 'Transaction calendar date' },
    { col: 'invoiceNo', type: 'String', ex: 'INV-2001', desc: 'Unique sales document code' },
    { col: 'customerName', type: 'String', ex: 'Acme Corp', desc: 'Client account designation' },
    { col: 'distributor', type: 'String', ex: 'Distro North', desc: 'Assigned commercial partner' },
    { col: 'product', type: 'String', ex: 'Premium Sensor', desc: 'Item or service descriptor' },
    { col: 'quantity', type: 'Number', ex: '50', desc: 'Billed unit volume' },
    { col: 'revenue', type: 'Number ($)', ex: '4500', desc: 'Gross billed monetary value' },
    { col: 'cost', type: 'Number ($)', ex: '1800', desc: 'Cost of goods sold (COGS)' },
    { col: 'discount', type: 'Number ($)', ex: '200', desc: 'Price concession / discount' },
    { col: 'creditDays', type: 'Number', ex: '30', desc: 'Contractual payment term days' },
    { col: 'outstandingAmount', type: 'Number ($)', ex: '500', desc: 'Uncollected receivable balance' },
    { col: 'region', type: 'String', ex: 'North', desc: 'Operating geographical sector' },
    { col: 'salesRep', type: 'String', ex: 'Alice', desc: 'Account executive in charge' }
  ];

  doc.setFillColor(241, 245, 249);
  doc.rect(margin, cursorY, pageWidth - margin * 2, 20, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(51, 65, 85);
  doc.text('COLUMN', margin + 8, cursorY + 13);
  doc.text('TYPE', margin + 110, cursorY + 13);
  doc.text('EXAMPLE', margin + 200, cursorY + 13);
  doc.text('DESCRIPTION', margin + 290, cursorY + 13);
  cursorY += 22;

  schemaItems.forEach((item, idx) => {
    if (idx % 2 === 0) {
      doc.setFillColor(248, 250, 252);
      doc.rect(margin, cursorY - 2, pageWidth - margin * 2, 17, 'F');
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(79, 70, 229);
    doc.text(item.col, margin + 8, cursorY + 10);

    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(item.type, margin + 110, cursorY + 10);

    doc.setTextColor(15, 23, 42);
    doc.text(item.ex, margin + 200, cursorY + 10);

    doc.setTextColor(71, 85, 105);
    doc.text(item.desc, margin + 290, cursorY + 10);

    cursorY += 18;
  });

  cursorY += 20;
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8.5);
  doc.setTextColor(100, 116, 139);
  doc.text('* AI Business Strategy Advisor also auto-maps alternative headers like "amount", "sales", "client", and "units".', margin, cursorY);

  doc.save('erp_sales_template_specification.pdf');
}

export const exportTemplateSpecToPdf = exportTemplateToPdf;

