// components/ExecutiveActionPlanCard.tsx — Layer 6 & 7: Conclusion, Recommendation & Actionable Items UI (Light Theme)
import React, { useState } from 'react';
import { 
  ExecutiveActionPlan, 
  RiskLevel 
} from '../types';
import { 
  Sparkles, 
  CheckCircle2, 
  Circle, 
  TrendingUp, 
  Clock, 
  User, 
  Download, 
  X, 
  CheckSquare, 
  Lightbulb, 
  Target 
} from 'lucide-react';

interface ExecutiveActionPlanCardProps {
  plan: ExecutiveActionPlan;
  onDismiss: () => void;
  isRtl?: boolean;
}

const ExecutiveActionPlanCard: React.FC<ExecutiveActionPlanCardProps> = ({
  plan,
  onDismiss,
  isRtl = false
}) => {
  const [completedTasks, setCompletedTasks] = useState<Record<string, boolean>>({});

  const toggleTask = (taskId: string) => {
    setCompletedTasks(prev => ({
      ...prev,
      [taskId]: !prev[taskId]
    }));
  };

  const completedCount = Object.values(completedTasks).filter(Boolean).length;
  const totalTasks = plan.actionItems.length;
  const progressPct = totalTasks > 0 ? Math.round((completedCount / totalTasks) * 100) : 0;

  const handleExport = () => {
    const mdContent = `# AI Executive Directive & Action Plan
**Generated:** ${plan.timestamp}
**Triggered By Voice Instruction:** "${plan.triggeredBy}"
**Risk Severity:** ${plan.riskLevel}

---

## 1. Executive Analytical Conclusion
${plan.conclusion}

${plan.rootCause ? `**Root Cause / Key Driver:**\n${plan.rootCause}\n` : ''}

---

## 2. Strategic Recommendations
${plan.recommendations.map((r, i) => `${i + 1}. ${r}`).join('\n')}

---

## 3. Actionable Execution Checklist
| Status | Priority | Task | Owner | Expected ROI | Deadline |
|--------|----------|------|-------|--------------|----------|
${plan.actionItems.map(item => {
  const status = completedTasks[item.id] ? '✅ Done' : '⏳ Pending';
  return `| ${status} | ${item.priority} | ${item.task} | ${item.owner || 'Commercial Lead'} | ${item.expectedRoi} | ${item.deadline || '14 Days'} |`;
}).join('\n')}

---
*Generated by Business Strategy Advisor AI Pipeline*
`;

    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Executive_Action_Plan_${Date.now()}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const getPriorityStyle = (priority: string) => {
    switch (priority) {
      case 'Immediate':
        return 'bg-rose-50 dark:bg-rose-950/60 text-rose-700 dark:text-rose-300 border border-rose-200 dark:border-rose-800';
      case 'High':
        return 'bg-amber-50 dark:bg-amber-950/60 text-amber-800 dark:text-amber-300 border border-amber-200 dark:border-amber-800';
      case 'Medium':
        return 'bg-blue-50 dark:bg-blue-950/60 text-blue-800 dark:text-blue-300 border border-blue-200 dark:border-blue-800';
      default:
        return 'bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-slate-700';
    }
  };

  const riskBadge = {
    [RiskLevel.HIGH]: 'bg-rose-50 dark:bg-rose-950/60 text-rose-700 dark:text-rose-300 border border-rose-200 dark:border-rose-800 font-bold',
    [RiskLevel.MEDIUM]: 'bg-amber-50 dark:bg-amber-950/60 text-amber-800 dark:text-amber-300 border border-amber-200 dark:border-amber-800 font-bold',
    [RiskLevel.LOW]: 'bg-emerald-50 dark:bg-emerald-950/60 text-emerald-800 dark:text-emerald-300 border border-emerald-200 dark:border-emerald-800 font-bold',
  }[plan.riskLevel] || 'bg-indigo-50 dark:bg-indigo-950/60 text-indigo-700 dark:text-indigo-300 border border-indigo-200 dark:border-indigo-800 font-bold';

  return (
    <div className={`bg-white dark:bg-slate-900 rounded-3xl p-5 md:p-7 shadow-sm border border-slate-200 dark:border-slate-800 animate-in fade-in slide-in-from-top-4 duration-300 relative overflow-hidden ${isRtl ? 'text-right' : 'text-left'}`} dir={isRtl ? 'rtl' : 'ltr'}>
      {/* Top Subtle Indigo-Purple Accent Bar */}
      <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-indigo-500 via-purple-500 to-emerald-500" />

      {/* Header Strip */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-100 dark:border-slate-800 pb-4 mb-5">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-2xl bg-indigo-50 dark:bg-indigo-950/60 border border-indigo-100 dark:border-indigo-800 flex items-center justify-center text-indigo-600 dark:text-indigo-400 shadow-2xs">
            <Sparkles className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
          </div>
          <div>
            <div className="flex items-center gap-2 flex-wrap">
              <h3 className="text-base md:text-lg font-bold tracking-tight text-slate-900 dark:text-slate-100 flex items-center gap-2">
                Executive Directive & Action Plan
              </h3>
              <span className={`text-[10px] uppercase px-2.5 py-0.5 rounded-full ${riskBadge}`}>
                {plan.riskLevel} Risk
              </span>
            </div>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5 flex items-center gap-1.5 flex-wrap">
              <span>Triggered by:</span>
              <span className="font-semibold text-slate-800 dark:text-slate-200 bg-slate-100 dark:bg-slate-800 px-2 py-0.5 rounded-md italic border border-slate-200/60 dark:border-slate-700">
                "{plan.triggeredBy}"
              </span>
              <span className="text-slate-400 dark:text-slate-500">• {plan.timestamp}</span>
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2 self-end sm:self-auto">
          <button
            onClick={handleExport}
            className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-50 dark:bg-slate-800 hover:bg-slate-100 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 rounded-xl text-xs font-semibold transition-all border border-slate-200 dark:border-slate-700 shadow-2xs cursor-pointer"
            title="Download Action Plan as Markdown"
          >
            <Download className="w-3.5 h-3.5 text-slate-500 dark:text-slate-400" />
            <span className="hidden sm:inline">Export Plan</span>
          </button>
          <button
            onClick={onDismiss}
            className="p-1.5 bg-slate-50 dark:bg-slate-800 hover:bg-slate-100 dark:hover:bg-slate-700 text-slate-400 dark:text-slate-300 hover:text-slate-600 dark:hover:text-slate-100 rounded-xl transition-colors border border-slate-200 dark:border-slate-700 cursor-pointer"
            title="Dismiss directive"
          >
            <X className="w-4 h-4" />
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Column: Conclusion & Recommendations (5 cols) */}
        <div className="lg:col-span-5 space-y-4">
          {/* Executive Conclusion */}
          <div className="bg-slate-50/80 dark:bg-slate-800/80 rounded-2xl p-4 md:p-5 border border-slate-200/70 dark:border-slate-700/70">
            <div className="flex items-center gap-2 text-indigo-700 dark:text-indigo-400 text-xs font-bold uppercase tracking-wider mb-2">
              <Target className="w-4 h-4 text-indigo-600 dark:text-indigo-400" />
              <span>Executive Conclusion</span>
            </div>
            <p className="text-sm md:text-base font-semibold text-slate-900 dark:text-slate-100 leading-relaxed">
              {plan.conclusion}
            </p>

            {plan.rootCause && (
              <div className="mt-3 pt-3 border-t border-slate-200/70 dark:border-slate-700/70 text-xs text-slate-600 dark:text-slate-300">
                <span className="font-bold text-slate-800 dark:text-slate-200">Root Cause: </span>
                <span>{plan.rootCause}</span>
              </div>
            )}
          </div>

          {/* Strategic Recommendations */}
          <div className="bg-slate-50/80 dark:bg-slate-800/80 rounded-2xl p-4 md:p-5 border border-slate-200/70 dark:border-slate-700/70">
            <div className="flex items-center gap-2 text-emerald-800 dark:text-emerald-400 text-xs font-bold uppercase tracking-wider mb-3">
              <Lightbulb className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
              <span>Strategic Recommendations</span>
            </div>
            <ul className="space-y-2.5 text-xs text-slate-700 dark:text-slate-300">
              {plan.recommendations.map((rec, idx) => (
                <li key={idx} className="flex items-start gap-2.5">
                  <div className="w-5 h-5 rounded-full bg-emerald-100 dark:bg-emerald-950/80 text-emerald-800 dark:text-emerald-300 border border-emerald-200 dark:border-emerald-800 flex items-center justify-center shrink-0 text-[10px] font-bold mt-0.5">
                    {idx + 1}
                  </div>
                  <span className="leading-relaxed font-medium text-slate-700 dark:text-slate-200">{rec}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* Right Column: Interactive Actionable Checklist (7 cols) */}
        <div className="lg:col-span-7 bg-slate-50/80 dark:bg-slate-800/80 rounded-2xl p-4 md:p-5 border border-slate-200/70 dark:border-slate-700/70 flex flex-col">
          {/* Checklist Header with Progress */}
          <div className="flex items-center justify-between gap-3 mb-4">
            <div className="flex items-center gap-2">
              <CheckSquare className="w-4 h-4 text-indigo-600 dark:text-indigo-400" />
              <h4 className="text-xs font-bold text-indigo-900 dark:text-indigo-300 uppercase tracking-wider">
                Actionable Execution Checklist ({completedCount}/{totalTasks})
              </h4>
            </div>
            <div className="flex items-center gap-2">
              <div className="w-24 bg-slate-200 dark:bg-slate-700 rounded-full h-2 overflow-hidden">
                <div 
                  className="bg-emerald-500 h-full transition-all duration-500 rounded-full" 
                  style={{ width: `${progressPct}%` }}
                />
              </div>
              <span className="text-[11px] font-bold text-emerald-700 dark:text-emerald-400">{progressPct}%</span>
            </div>
          </div>

          {/* Items List */}
          <div className="space-y-2.5 flex-1 overflow-y-auto max-h-[360px] pr-1">
            {plan.actionItems.map((item) => {
              const isDone = !!completedTasks[item.id];
              return (
                <div
                  key={item.id}
                  onClick={() => toggleTask(item.id)}
                  className={`p-3.5 rounded-xl border transition-all cursor-pointer select-none ${
                    isDone
                      ? 'bg-slate-100/90 dark:bg-slate-800/40 border-slate-200 dark:border-slate-800 text-slate-400 dark:text-slate-500 opacity-75'
                      : 'bg-white dark:bg-slate-900 hover:bg-indigo-50/40 dark:hover:bg-slate-800/80 border-slate-200 dark:border-slate-700 shadow-2xs hover:border-indigo-300 dark:hover:border-indigo-600 text-slate-800 dark:text-slate-200'
                  }`}
                >
                  <div className="flex items-start gap-3">
                    <button
                      type="button"
                      className="mt-0.5 text-slate-400 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors shrink-0 cursor-pointer"
                    >
                      {isDone ? (
                        <CheckCircle2 className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
                      ) : (
                        <Circle className="w-4 h-4 text-slate-300 dark:text-slate-600" />
                      )}
                    </button>

                    <div className="flex-1 min-w-0">
                      <div className="flex items-center justify-between gap-2 flex-wrap">
                        <span className={`text-xs font-bold ${isDone ? 'line-through text-slate-400 dark:text-slate-500' : 'text-slate-900 dark:text-slate-100'}`}>
                          {item.task}
                        </span>
                        <span className={`text-[9px] font-bold px-2 py-0.5 rounded-md uppercase tracking-wider ${getPriorityStyle(item.priority)}`}>
                          {item.priority}
                        </span>
                      </div>

                      <div className="flex items-center gap-3 mt-2 flex-wrap text-[11px] text-slate-600 dark:text-slate-400">
                        {item.owner && (
                          <span className="flex items-center gap-1">
                            <User className="w-3 h-3 text-slate-400" />
                            <span className="text-slate-600 dark:text-slate-300">{item.owner}</span>
                          </span>
                        )}
                        <span className="flex items-center gap-1 text-emerald-700 dark:text-emerald-400 font-bold">
                          <TrendingUp className="w-3 h-3 text-emerald-600 dark:text-emerald-400" />
                          <span>ROI: {item.expectedRoi}</span>
                        </span>
                        {item.deadline && (
                          <span className="flex items-center gap-1 text-slate-400 dark:text-slate-500">
                            <Clock className="w-3 h-3" />
                            <span>{item.deadline}</span>
                          </span>
                        )}
                      </div>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>

          <p className="text-[10px] text-slate-400 dark:text-slate-500 mt-3 text-center">
            Click any task above to check it off as executed. Export the action plan to share with regional commercial leads.
          </p>
        </div>
      </div>
    </div>
  );
};

export default ExecutiveActionPlanCard;
